FROM maven:3.9.9-eclipse-temurin-21

WORKDIR /app

# Copy only pom first to cache dependencies
COPY pom.xml .
RUN mvn dependency:go-offline

# Copy source (will be overridden by volume mount in dev)
COPY src ./src

EXPOSE 8080  
EXPOSE 5005   

CMD ["mvn", "spring-boot:run", "-Dspring-boot.run.jvmArguments=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"]